# config.yml

backend:
  name: git-gateway
  branch: staging # Branch to update (optional; defaults to master)
media_folder: 'assets/images'
collections:
  - name: 'paintings'
    create: true
    label: 'Painting'
    folder: '_paintings/'
    slug: "{{ slug }}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "painting"}
      - {label: "Identifier", name: "identifier", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}